# -*- coding: utf-8 -*-
"""
/***************************************************************************
 AreaQueimadaPlugin
                                 A QGIS plugin
 Cálculo de dNBR e vetorização automática de cicatrizes de fogo
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-03-12
        copyright            : (C) 2026 by Leandro Paixao
        email                : leandroluizp@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Leandro Paixao'
__date__ = '2026-03-12'
__copyright__ = '(C) 2026 by Leandro Paixao'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load AreaQueimadaPlugin class from file AreaQueimadaPlugin.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .area_queimada import AreaQueimadaPlugin
    return AreaQueimadaPlugin(iface)
