# -*- coding: utf-8 -*-

"""
/***************************************************************************
 AreaQueimadaPlugin
                                 A QGIS plugin
 Cálculo de dNBR e vetorização automática de cicatrizes de fogo
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-03-12
        copyright            : (C) 2026 by Leandro Paixao
        email                : leandroluizp@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Leandro Paixao'
__date__ = '2026-03-12'
__copyright__ = '(C) 2026 by Leandro Paixao'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

from qgis.core import (QgsProcessing,
                       QgsProcessingAlgorithm,
                       QgsProcessingMultiStepFeedback,
                       QgsProcessingParameterRasterLayer,
                       QgsProcessingParameterNumber,
                       QgsProcessingParameterVectorDestination)
import processing

class AreaQueimadaPluginAlgorithm(QgsProcessingAlgorithm):
    # Nomes técnicos que você definiu
    def name(self):
        return 'area_queimada'

    def displayName(self):
        return 'Detecção de Área Queimada (dNBR)'

    def group(self):
        return 'Processamento de Imagens'

    def groupId(self):
        return 'processamento_imagens'

    def createInstance(self):
        return AreaQueimadaPluginAlgorithm()

    def initAlgorithm(self, config=None):
        self.addParameter(QgsProcessingParameterRasterLayer('nir_antes', 'NIR Antes', defaultValue=None))
        self.addParameter(QgsProcessingParameterRasterLayer('swir_antes', 'SWIR Antes', defaultValue=None))
        self.addParameter(QgsProcessingParameterRasterLayer('nir_depois', 'NIR Depois', defaultValue=None))
        self.addParameter(QgsProcessingParameterRasterLayer('swir_depois', 'SWIR Depois', defaultValue=None))
        self.addParameter(QgsProcessingParameterNumber(
            'limiar', 
            'Limiar de Severidade (dNBR)', 
            type=QgsProcessingParameterNumber.Double, 
            defaultValue=0.1,
            minValue=-1.0, 
            maxValue=1.0
        ))
        
        self.addParameter(QgsProcessingParameterVectorDestination('Area_queimada', 'Cicatrizes de Queimada (Vetor)', type=QgsProcessing.TypeVectorPolygon, createByDefault=True, defaultValue=None))

    def processAlgorithm(self, parameters, context, model_feedback):
        # 5 passos: 2 NBRs + dNBR + Poligonizar + Filtrar Fundo
        feedback = QgsProcessingMultiStepFeedback(5, model_feedback)
        results = {}
        outputs = {}

        limiar_usuario = self.parameterAsDouble(parameters, 'limiar', context)
        
        # 1. NBR ANTES
        alg_params = {
            'EXPRESSION': '( "A@1" - "B@1") / ( "A@1" + "B@1" )',
            'LAYERS': [parameters['nir_antes'], parameters['swir_antes']],
            'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
        }
        outputs['Nbr_antes'] = processing.run('native:modelerrastercalc', alg_params, context=context, feedback=feedback, is_child_algorithm=True)

        feedback.setCurrentStep(1)
        # 2. NBR DEPOIS
        alg_params = {
            'EXPRESSION': '( "A@1" - "B@1") / ( "A@1" + "B@1" )',
            'LAYERS': [parameters['nir_depois'], parameters['swir_depois']],
            'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
        }
        outputs['Nbr_depois'] = processing.run('native:modelerrastercalc', alg_params, context=context, feedback=feedback, is_child_algorithm=True)

        feedback.setCurrentStep(2)
        # 3. DNBR (Agora com o limiar dinâmico na expressão)
        alg_params = {
            'EXPRESSION': f'( "A@1" - "B@1" ) >= {limiar_usuario}', # Usamos f-string para injetar o valor
            'LAYERS': [outputs['Nbr_antes']['OUTPUT'], outputs['Nbr_depois']['OUTPUT']],
            'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
        }
        outputs['Dnbr'] = processing.run('native:modelerrastercalc', alg_params, context=context, feedback=feedback, is_child_algorithm=True)

        feedback.setCurrentStep(3)
        # 4. Vetorização (Gera o fundo DN=0 e a queimada DN=1)
        alg_params = {
            'BAND': 1, 'FIELD': 'DN',
            'INPUT': outputs['Dnbr']['OUTPUT'],
            'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
        }
        outputs['VetorBruto'] = processing.run('gdal:polygonize', alg_params, context=context, feedback=feedback, is_child_algorithm=True)

        feedback.setCurrentStep(4)
        # 5. REPARO: Extrair apenas DN=1 (Remove o fundo)
        alg_params = {
            'FIELD': 'DN',
            'OPERATOR': 0, # Igual a
            'VALUE': '1',
            'INPUT': outputs['VetorBruto']['OUTPUT'],
            'OUTPUT': parameters['Area_queimada']
        }
        outputs['FiltroFinal'] = processing.run('native:extractbyattribute', alg_params, context=context, feedback=feedback, is_child_algorithm=True)

        results['Area_queimada'] = outputs['FiltroFinal']['OUTPUT']
        return results