# -*- coding: utf-8 -*-

"""
/***************************************************************************
 AreaQueimadaPlugin
                                 A QGIS plugin
 Cálculo de dNBR e vetorização automática de cicatrizes de fogo
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-03-12
        copyright            : (C) 2026 by Leandro Paixao
        email                : leandroluizp@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Leandro Paixao'
__date__ = '2026-03-12'
__copyright__ = '(C) 2026 by Leandro Paixao'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

from qgis.core import QgsProcessingProvider
from .area_queimada_algorithm import AreaQueimadaPluginAlgorithm


class AreaQueimadaPluginProvider(QgsProcessingProvider):

    def __init__(self):
        """
        Default constructor.
        """
        QgsProcessingProvider.__init__(self)

    def unload(self):
        """
        Unloads the provider. Any tear-down steps required by the provider
        should be implemented here.
        """
        pass

    def loadAlgorithms(self):
        """
        Loads all algorithms belonging to this provider.
        """
        self.addAlgorithm(AreaQueimadaPluginAlgorithm())
        # add additional algorithms here
        # self.addAlgorithm(MyOtherAlgorithm())

    def id(self):
        """
        ID interno (endereço para o QGIS). 
        Deve ser curto e sem espaços.
        """
        return 'area_queimada' # Mude para isso

    def name(self):
        """
        Nome visual (o que aparece na Caixa de Ferramentas). 
        Pode ter espaços e acentos.
        """
        return self.tr('Ferramentas Área Queimada')
    def icon(self):
        """
        Should return a QIcon which is used for your provider inside
        the Processing toolbox.
        """
        return QgsProcessingProvider.icon(self)

    def longName(self):
        """
        Returns the a longer version of the provider name, which can include
        extra details such as version numbers. E.g. "Lastools LIDAR tools
        (version 2.2.1)". This string should be localised. The default
        implementation returns the same string as name().
        """
        return self.name()
