# -*- coding: utf-8 -*-

"""
/***************************************************************************
 AreaQueimadaPlugin
                                 A QGIS plugin
 Cálculo de dNBR e vetorização automática de cicatrizes de fogo
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-03-12
        copyright            : (C) 2026 by Leandro Paixao
        email                : leandroluizp@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Leandro Paixao'
__date__ = '2026-03-12'
__copyright__ = '(C) 2026 by Leandro Paixao'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'
# -*- coding: utf-8 -*-

# -*- coding: utf-8 -*-

import os
from qgis.PyQt.QtCore import QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction
from qgis.core import QgsApplication
import processing

# Importa o seu provedor (ajuste o nome se necessário)
from .area_queimada_provider import AreaQueimadaPluginProvider

class AreaQueimadaPlugin(object):
    def __init__(self, iface):
        self.iface = iface
        self.provider = AreaQueimadaPluginProvider()
        self.plugin_dir = os.path.dirname(__file__)

    def initGui(self):
        """Cria o menu dentro do menu Raster do QGIS"""
        
        # 1. Configura o ícone e a Ação
        icon_path = os.path.join(self.plugin_dir, 'icon.png')
        icon = QIcon(icon_path)
        
        self.action = QAction(icon, "Detecção de Área Queimada (dNBR)", self.iface.mainWindow())
        self.action.triggered.connect(self.run)
        self.action.setCheckable(False)

        # 2. Adiciona especificamente ao Menu RASTER (Igual ao KML Tools)
        # O primeiro argumento é o nome do Sub-menu, o segundo é a ação
        self.iface.addPluginToRasterMenu("Monitoramento de Queimadas", self.action)

        # 3. Adiciona o ícone na barra de ferramentas para facilitar
        self.iface.addToolBarIcon(self.action)

        # 4. Registra o provedor na caixa de ferramentas
        QgsApplication.processingRegistry().addProvider(self.provider)

    def unload(self):
        """Remove o plugin e limpa a memória para não quebrar o menu Raster"""
        # Remove do menu Raster
        self.iface.removePluginRasterMenu("Monitoramento de Queimadas", self.action)
        
        # Remove o ícone da barra de ferramentas
        self.iface.removeToolBarIcon(self.action)
        
        # Deleta a ação da memória
        self.action.deleteLater()
        
        # Remove da Caixa de Ferramentas
        QgsApplication.processingRegistry().removeProvider(self.provider)

    def tr(self, message):
        return QCoreApplication.translate('AreaQueimadaPlugin', message)

    def run(self):
        """Abre a janela do seu algoritmo"""
        # Certifique-se que o ID 'area_queimada:area_queimada' é o mesmo do seu _algorithm.py
        import processing
        processing.execAlgorithmDialog('area_queimada:area_queimada', {})